[package]
authors = ["Ashley Blewer <ashley.blewer@gmail.com>"]
categories = ["wasm"]
description = "media-collection-viewer"
edition = "2018"
license = "Apache-2.0/MIT"
name = "yew-app"
readme = "./README.md"
repository = "TODO"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
yew = "0.17.3"
yew-router = { version="0.14.0", features = ["web_sys"] }

wasm-bindgen = "0.2.64"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2.0"
wee_alloc = "0.4.5"

js-sys = "0.3"
web-sys = "0.3"
stdweb = "0.4.20"

serde = "1.0.124"
serde_derive = "1.0.124"
serde_json = "1.0.64"


[dev-dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "HtmlCollection",
]
